# Generated by Django 5.1.3 on 2024-11-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='is_open_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolmock_app.answeroption'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='written_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
