# Generated by Django 5.1.4 on 2024-12-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0003_alter_studentanswer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_finished',
        ),
    ]
