# Generated by Django 5.1.4 on 2024-12-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0004_remove_test_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmock_app.profile'),
        ),
    ]
