# Generated by Django 5.1.4 on 2025-01-07 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='finished_at',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_date',
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
