# Generated by Django 5.1.4 on 2025-01-07 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0002_rename_finished_at_test_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='end_time',
            new_name='finished_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
