# Generated by Django 5.1.5 on 2025-02-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0003_rename_end_time_test_finished_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_open_ended',
        ),
    ]
